name: Application CI/CD

on:
  push:
    branches: [ main ]
  #  paths:
  #    - "product-app/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1  
  CONTAINER_NAME: product-app

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up environment name
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: Set up ECS variables
        run: |
          echo "ECR_REPOSITORY=$ENV-$CONTAINER_NAME-ecr" >> $GITHUB_ENV
          echo "ECS_CLUSTER=$ENV-$CONTAINER_NAME-cluster" >> $GITHUB_ENV
          echo "ECS_SERVICE=$ENV-$CONTAINER_NAME-service" >> $GITHUB_ENV
          echo "TASK_FAMILY=task-definition-$ENV-$CONTAINER_NAME" >> $GITHUB_ENV       

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR
        run: mvn clean package -DskipTests
        working-directory: ./product-app

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/ECSFargateGitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image

        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
                       -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG          
        working-directory: ./product-app

      - name: Update ECS Task Definition
        id: task-def
        run: |
          TASK_DEF=$(aws ecs describe-task-definition \
            --task-definition $TASK_FAMILY)

          NEW_IMAGE="${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:${{ github.sha }}"

          UPDATED=$(echo $TASK_DEF | jq \
            --arg IMAGE "$NEW_IMAGE" \
            --arg NAME "$CONTAINER_NAME" \
            '.taskDefinition
            | .containerDefinitions
            |= map(if .name == $NAME then .image = $IMAGE else . end)
            | del(
                .taskDefinitionArn,
                .revision,
                .status,
                .requiresAttributes,
                .compatibilities,
                .registeredAt,
                .registeredBy
              )')

          echo "$UPDATED" > new-task-def.json

          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "NEW_TASK_DEF_ARN=$NEW_TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition $NEW_TASK_DEF_ARN \
            --force-new-deployment