name: Application CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - "product-app/src/**"
      - "product-app/pom.xml"
      - "product-app/Dockerfile"

  pull_request:
    branches: [ main ]
    paths:
     - "product-app/src/**"
     - "product-app/pom.xml"
     - "product-app/Dockerfile"

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: product-app-ecr
  ECS_CLUSTER: product-app-cluster
  ECS_SERVICE: product-app-service
  CONTAINER_NAME: product-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: ./mvnw clean verify
        working-directory: product-app

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/ECSFargateGitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        if: github.event_name == 'push'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        if: github.event_name == 'push'
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} ./product-app

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Update ECS Service
        run: |
          aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment \
          --desired-count 1
